version: "3.1"

volumes:
  data: {} 

services:
  mongo:
    image: mongo:8.0
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ligne8
      MONGO_INITDB_ROOT_PASSWORD: ligne8password
    volumes:
      - data:/data/db/
