version: "3.8"

services:
  mongo:
    image: mongo:8.0
    container_name: mongo-assets
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ligne8
      MONGO_INITDB_ROOT_PASSWORD: ligne8password
    volumes:
      - ./db_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5151:5151"
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mongodb://ligne8:ligne8password@mongo:27017